# Generated by Django 5.1.4 on 2025-02-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_curd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='fullName',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='fullname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
